need to check properly
VolodymyrPyts/project4_project_team pull request #7
Opened 2022-07-15 16:40 UTC by Karnydal

made main card fetch and popular today, but please check properly because I`m not sure

2022-07-15 18:27 UTC, VolodymyrPyts approved these changes
виправь експорт

2022-07-15 18:30 UTC, VolodymyrPyts requested changes

2022-07-15 18:30 UTC, VolodymyrPyts commented on src/fetchMain.js
> +export default class FilmsApiService {
або цей виправь або іменований

2022-07-15 18:30 UTC, VolodymyrPyts commented on src/index.js
> +import './fetchMain';
import імя from "./js/імя.джс"; це якщо дефаулт експорт
import { Notify } from 'notiflix/build/notiflix-notify-aio'; іменований

2022-07-16 07:13 UTC, Karnydal commented on src/index.js
> +import './fetchMain';
Вже переробив))))

2022-07-16 09:30 UTC, VolodymyrPyts approved these changes

2022-07-16 09:30 UTC, merged